# Generated by Django 2.1 on 2018-12-20 08:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(max_length=100, verbose_name='Headline')),
                ('text', models.TextField(max_length=2000, verbose_name='Text')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created time')),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Client name')),
                ('email', models.EmailField(blank=True, max_length=100, null=True, verbose_name='Email')),
                ('password', models.CharField(max_length=16, verbose_name='Password')),
                ('favorites', models.ManyToManyField(blank=True, related_name='favored_by', to='webapp.Article', verbose_name='Favorites')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(max_length=500, verbose_name='Comment')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created time')),
                ('answer_on_comment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='comments', to='webapp.Comment', verbose_name='Answer')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='comments', to='webapp.Article', verbose_name='Article')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='webapp.Client', verbose_name='Author')),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created time')),
                ('status', models.CharField(choices=[('Ужас', 'Ужас'), ('Не очень', 'Не очень'), ('Пойдет', 'Пойдет'), ('Жакшы', 'Жакшы'), ('Зынк', 'Зынк')], default='Пойдет', max_length=10, verbose_name='Rating')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='client_rating', to='webapp.Article', verbose_name='Article')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='article_rating', to='webapp.Client', verbose_name='Author')),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='article', to='webapp.Client', verbose_name='Author'),
        ),
    ]
